"""
Bringer RAG System — Orchestration Pipeline

The central brain of the application. It receives a user query, triggers the
hybrid retrieval engine, formats the resulting contexts into a strict prompt,
sends it to the LM Studio LLM client, and handles the token streaming and source citations.
"""

import time
from typing import List, Dict, Any, Generator, Optional, Tuple
from rich.console import Console

import sys
import os
# Add project root to path so we can import config
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
import config

from src.modules.hybrid_retriever import HybridRetriever
from src.modules.prompt_builder import PromptBuilder
from src.modules.llm_client import LLMClient

console = Console()

class RAGPipeline:
    def __init__(self):
        """Initializes all downstream engines required for full text Generation."""
        # Note: We initialize these lazily or as singletons where appropriate 
        # so we don't blow up VRAM on import.
        self.retriever = HybridRetriever()
        self.prompt_builder = PromptBuilder()
        self.llm_client = LLMClient()

    def _extract_sources(self, chunks: List[Dict[str, Any]]) -> List[str]:
        """
        Deduplicates and formats the source metadata from the retrieved chunks
        into clean citation strings.
        """
        sources = set()
        for chunk in chunks:
            source_file = chunk["metadata"].get("source_file", "Unknown")
            chunk_index = chunk["metadata"].get("chunk_index", "N/A")
            page_number = chunk["metadata"].get("page_number")
            
            if page_number is not None:
                sources.add(f"{source_file} (page {page_number} | chunk {chunk_index})")
            else:
                sources.add(f"{source_file} (chunk {chunk_index})")
            
        return sorted(list(sources))

    def run_rag(self, query: str) -> Generator[str, None, None]:
        """
        Orchestrates the entire RAG flow: Retrieve -> Prompt -> Stream LLM.
        
        Yields:
            Tokens generated by the LLM (or status messages), 
            and finally the formatted Sources block.
        """
        console.print(f"\n[bold cyan]Query:[/bold cyan] [italic]{query}[/italic]")
        
        # 1. Retrieval
        t0 = time.perf_counter()
        chunks = self.retriever.retrieve(query)
        t_retrieval = time.perf_counter() - t0
        
        if not chunks:
            yield "\nNo relevant information was found in the indexed documents."
            return
            
        console.print(f"[dim]Hybrid retrieval results: {len(chunks)} ({t_retrieval*1000:.1f}ms)[/dim]")
        
        # 2. Prompt Building
        t0 = time.perf_counter()
        messages, token_estimate = self.prompt_builder.build_prompt(query, chunks)
        t_prompt = time.perf_counter() - t0
        
        console.print(f"[dim]Prompt tokens: ~{token_estimate} ({t_prompt*1000:.1f}ms)[/dim]")
        console.print("[dim]LLM generation started...[/dim]\n")
        
        # 3. LLM Streaming
        try:
            for token in self.llm_client.stream(messages):
                yield token
        except Exception as e:
            yield f"\n\n[Error during LLM generation: {str(e)}]"
            return
            
        # 4. Append Sources Citation
        sources = self._extract_sources(chunks)
        yield "\n\n[bold cyan]Sources:[/bold cyan]\n"
        for source in sources:
            yield f"• {source}\n"


# Quick test trigger block (only runs if executed directly)
if __name__ == "__main__":
    if len(sys.argv) > 1:
        test_query = " ".join(sys.argv[1:])
    else:
        test_query = "What is a wired LAN?"
        
    console.print(f"\n[bold magenta]--- RAG Pipeline Test ---[/bold magenta]")
    
    pipeline = RAGPipeline()
    
    # We simulate a rich streaming terminal output
    print("\nAnswer: ", end="", flush=True)
    for chunk in pipeline.run_rag(test_query):
        # We handle rich-compatible string clearing or just print directly
        # Note: in a real CLI, rich's Live updater is prettier, but standard stdout is safest here.
        print(chunk, end="", flush=True)
    print("\n\n[bold green]Test Complete![/bold green]")
